version: '3'

services:
  nginx:
    image: mrpaulblack/bolby:latest
    restart: always
    networks:
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "${LOKI_URL}"
        loki-external-labels: env=${ENV}
        loki-relabel-config: |
          - action: labeldrop
            regex: filename
    labels:
      - traefik.enable=true
      - traefik.http.routers.bolby.rule=Host({DOMAIN_LIST})&&Method(`GET`,`HEAD`)
      - traefik.http.routers.bolby.entrypoints=https
      - traefik.http.routers.bolby.tls=true
      - traefik.http.routers.bolby.middlewares=external-secure,www-redirect
      # comp with bing bot and other non tls13 stuff
      - traefik.http.routers.bolby.tls.options=tls12@file
      # redirect root domain to www.rootdomain.tld
      - traefik.http.middlewares.www-redirect.redirectregex.regex=${REGEX_REDIRECT}
      - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://{DOMAIN}
      # bolby-other router for all the other domains pointing to www.rootdomain.tld, 301 perma for paul-online.tech and canonical header
      - traefik.http.routers.bolby-other.rule=Host(${OTHER_HOSTS})&&Method(`GET`,`HEAD`)
      - traefik.http.routers.bolby-other.entrypoints=https
      - traefik.http.routers.bolby-other.tls=true
      - traefik.http.routers.bolby-other.middlewares=external-secure,bolby-canonical,bolby-redirect
      - traefik.http.routers.bolby-other.service=noop@internal
      # comp with bing bot and other non tls13 stuff
      - traefik.http.routers.bolby-other.tls.options=tls12@file
      # set canonical url to www.rootdomain.tld
      - traefik.http.middlewares.bolby-canonical.headers.customresponseheaders.Link=<https://{DOMAIN}>; rel="canonical"
      # redirect other domains to www.rootdoamin.tld domain
      - traefik.http.middlewares.bolby-redirect.redirectregex.regex=${OTHER_REGEX}
      - traefik.http.middlewares.bolby-redirect.redirectregex.replacement=https://{DOMAIN}

networks:
  proxy:
    external: true
